version: '3'
services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 3000:3000
  web:
    container_name: widget
    build:
      context: ./widget
    ports:
      - 8080:80
    depends_on:
      - server
